name: CI pipeline - Development env

on:
  push:
    branches:
      - dev

jobs:
  build-deploy:
    name: Build and deploy with GitHub Actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Run tests
        run: mvn -B test --file pom.xml

      - name: Build with Maven
        run: |
          echo "Build on branch dev"
          mvn clean package -DskipTests
