name: CI pipeline - Product env

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy with GitHub Actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build with Maven
        run: |
          echo "Build on product environment"
          mvn clean package -DskipTests
